# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: converter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onverter.proto\x12\tconverter\"H\n\x0e\x43onvertRequest\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.converter.ConversionType\x12\r\n\x05value\x18\x02 \x01(\x01\"~\n\x0f\x43onvertResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\x11\n\tunit_from\x18\x02 \x01(\t\x12\x0f\n\x07unit_to\x18\x03 \x01(\t\x12\x0f\n\x07\x66ormula\x18\x04 \x01(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x15\n\rerror_message\x18\x06 \x01(\t\"\x0f\n\rHealthRequest\"5\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bserver_info\x18\x02 \x01(\t*\xa6\x01\n\x0e\x43onversionType\x12\x19\n\x15\x43\x45LSIUS_TO_FAHRENHEIT\x10\x00\x12\x19\n\x15\x46\x41HRENHEIT_TO_CELSIUS\x10\x01\x12\x14\n\x10SOLES_TO_DOLARES\x10\x02\x12\x14\n\x10\x44OLARES_TO_SOLES\x10\x03\x12\x18\n\x14KILOMETROS_TO_MILLAS\x10\x04\x12\x18\n\x14MILLAS_TO_KILOMETROS\x10\x05\x32\x91\x01\n\tConverter\x12@\n\x07\x43onvert\x12\x19.converter.ConvertRequest\x1a\x1a.converter.ConvertResponse\x12\x42\n\x0bHealthCheck\x12\x18.converter.HealthRequest\x1a\x19.converter.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERSIONTYPE']._serialized_start=305
  _globals['_CONVERSIONTYPE']._serialized_end=471
  _globals['_CONVERTREQUEST']._serialized_start=30
  _globals['_CONVERTREQUEST']._serialized_end=102
  _globals['_CONVERTRESPONSE']._serialized_start=104
  _globals['_CONVERTRESPONSE']._serialized_end=230
  _globals['_HEALTHREQUEST']._serialized_start=232
  _globals['_HEALTHREQUEST']._serialized_end=247
  _globals['_HEALTHRESPONSE']._serialized_start=249
  _globals['_HEALTHRESPONSE']._serialized_end=302
  _globals['_CONVERTER']._serialized_start=474
  _globals['_CONVERTER']._serialized_end=619
# @@protoc_insertion_point(module_scope)
